import type { Metadata } from "next";
import { Geist, Geist_Mono, Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Homepage/Navber";
import Footer from "@/components/Homepage/Footer";
import WorkoutProvider from "@/Context/WorkoutContext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`${oswald.className} bg-black text-white min-h-screen`}>
        <WorkoutProvider>
          <Navbar />
          {children}
          <Footer />
        </WorkoutProvider>

       <ToastContainer 
           
          theme="dark" 
        />
      </body>
    </html>
  );
}
